// Generated by gencpp from file transformtrack/DropVelocityResponse.msg
// DO NOT EDIT!


#ifndef TRANSFORMTRACK_MESSAGE_DROPVELOCITYRESPONSE_H
#define TRANSFORMTRACK_MESSAGE_DROPVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transformtrack
{
template <class ContainerAllocator>
struct DropVelocityResponse_
{
  typedef DropVelocityResponse_<ContainerAllocator> Type;

  DropVelocityResponse_()
    : done(false)  {
    }
  DropVelocityResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::transformtrack::DropVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transformtrack::DropVelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DropVelocityResponse_

typedef ::transformtrack::DropVelocityResponse_<std::allocator<void> > DropVelocityResponse;

typedef boost::shared_ptr< ::transformtrack::DropVelocityResponse > DropVelocityResponsePtr;
typedef boost::shared_ptr< ::transformtrack::DropVelocityResponse const> DropVelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transformtrack::DropVelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transformtrack::DropVelocityResponse_<ContainerAllocator1> & lhs, const ::transformtrack::DropVelocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transformtrack::DropVelocityResponse_<ContainerAllocator1> & lhs, const ::transformtrack::DropVelocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transformtrack

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transformtrack::DropVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transformtrack::DropVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transformtrack::DropVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::transformtrack::DropVelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transformtrack/DropVelocityResponse";
  }

  static const char* value(const ::transformtrack::DropVelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
;
  }

  static const char* value(const ::transformtrack::DropVelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DropVelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transformtrack::DropVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transformtrack::DropVelocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSFORMTRACK_MESSAGE_DROPVELOCITYRESPONSE_H
