// Generated by gencpp from file transformtrack/DropVelocity.msg
// DO NOT EDIT!


#ifndef TRANSFORMTRACK_MESSAGE_DROPVELOCITY_H
#define TRANSFORMTRACK_MESSAGE_DROPVELOCITY_H

#include <ros/service_traits.h>


#include <transformtrack/DropVelocityRequest.h>
#include <transformtrack/DropVelocityResponse.h>


namespace transformtrack
{

struct DropVelocity
{

typedef DropVelocityRequest Request;
typedef DropVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DropVelocity
} // namespace transformtrack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::transformtrack::DropVelocity > {
  static const char* value()
  {
    return "2b47bafdc4c00e27a7f0cfd76dc9037e";
  }

  static const char* value(const ::transformtrack::DropVelocity&) { return value(); }
};

template<>
struct DataType< ::transformtrack::DropVelocity > {
  static const char* value()
  {
    return "transformtrack/DropVelocity";
  }

  static const char* value(const ::transformtrack::DropVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::transformtrack::DropVelocityRequest> should match
// service_traits::MD5Sum< ::transformtrack::DropVelocity >
template<>
struct MD5Sum< ::transformtrack::DropVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::transformtrack::DropVelocity >::value();
  }
  static const char* value(const ::transformtrack::DropVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::transformtrack::DropVelocityRequest> should match
// service_traits::DataType< ::transformtrack::DropVelocity >
template<>
struct DataType< ::transformtrack::DropVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::transformtrack::DropVelocity >::value();
  }
  static const char* value(const ::transformtrack::DropVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::transformtrack::DropVelocityResponse> should match
// service_traits::MD5Sum< ::transformtrack::DropVelocity >
template<>
struct MD5Sum< ::transformtrack::DropVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::transformtrack::DropVelocity >::value();
  }
  static const char* value(const ::transformtrack::DropVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::transformtrack::DropVelocityResponse> should match
// service_traits::DataType< ::transformtrack::DropVelocity >
template<>
struct DataType< ::transformtrack::DropVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::transformtrack::DropVelocity >::value();
  }
  static const char* value(const ::transformtrack::DropVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRANSFORMTRACK_MESSAGE_DROPVELOCITY_H
