// Generated by gencpp from file transformtrack/TransformBatch.msg
// DO NOT EDIT!


#ifndef TRANSFORMTRACK_MESSAGE_TRANSFORMBATCH_H
#define TRANSFORMTRACK_MESSAGE_TRANSFORMBATCH_H

#include <ros/service_traits.h>


#include <transformtrack/TransformBatchRequest.h>
#include <transformtrack/TransformBatchResponse.h>


namespace transformtrack
{

struct TransformBatch
{

typedef TransformBatchRequest Request;
typedef TransformBatchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransformBatch
} // namespace transformtrack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::transformtrack::TransformBatch > {
  static const char* value()
  {
    return "d17c54b06f263044d75d6d03617a9ba1";
  }

  static const char* value(const ::transformtrack::TransformBatch&) { return value(); }
};

template<>
struct DataType< ::transformtrack::TransformBatch > {
  static const char* value()
  {
    return "transformtrack/TransformBatch";
  }

  static const char* value(const ::transformtrack::TransformBatch&) { return value(); }
};


// service_traits::MD5Sum< ::transformtrack::TransformBatchRequest> should match
// service_traits::MD5Sum< ::transformtrack::TransformBatch >
template<>
struct MD5Sum< ::transformtrack::TransformBatchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::transformtrack::TransformBatch >::value();
  }
  static const char* value(const ::transformtrack::TransformBatchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::transformtrack::TransformBatchRequest> should match
// service_traits::DataType< ::transformtrack::TransformBatch >
template<>
struct DataType< ::transformtrack::TransformBatchRequest>
{
  static const char* value()
  {
    return DataType< ::transformtrack::TransformBatch >::value();
  }
  static const char* value(const ::transformtrack::TransformBatchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::transformtrack::TransformBatchResponse> should match
// service_traits::MD5Sum< ::transformtrack::TransformBatch >
template<>
struct MD5Sum< ::transformtrack::TransformBatchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::transformtrack::TransformBatch >::value();
  }
  static const char* value(const ::transformtrack::TransformBatchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::transformtrack::TransformBatchResponse> should match
// service_traits::DataType< ::transformtrack::TransformBatch >
template<>
struct DataType< ::transformtrack::TransformBatchResponse>
{
  static const char* value()
  {
    return DataType< ::transformtrack::TransformBatch >::value();
  }
  static const char* value(const ::transformtrack::TransformBatchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRANSFORMTRACK_MESSAGE_TRANSFORMBATCH_H
