// Generated by gencpp from file trafficsigns/TrafficSignStatus.msg
// DO NOT EDIT!


#ifndef TRAFFICSIGNS_MESSAGE_TRAFFICSIGNSTATUS_H
#define TRAFFICSIGNS_MESSAGE_TRAFFICSIGNSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <trafficsigns/TrafficSign.h>

namespace trafficsigns
{
template <class ContainerAllocator>
struct TrafficSignStatus_
{
  typedef TrafficSignStatus_<ContainerAllocator> Type;

  TrafficSignStatus_()
    : header()
    , traffic_signs()  {
    }
  TrafficSignStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , traffic_signs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::trafficsigns::TrafficSign_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::trafficsigns::TrafficSign_<ContainerAllocator> >> _traffic_signs_type;
  _traffic_signs_type traffic_signs;





  typedef boost::shared_ptr< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficSignStatus_

typedef ::trafficsigns::TrafficSignStatus_<std::allocator<void> > TrafficSignStatus;

typedef boost::shared_ptr< ::trafficsigns::TrafficSignStatus > TrafficSignStatusPtr;
typedef boost::shared_ptr< ::trafficsigns::TrafficSignStatus const> TrafficSignStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trafficsigns::TrafficSignStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::trafficsigns::TrafficSignStatus_<ContainerAllocator1> & lhs, const ::trafficsigns::TrafficSignStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.traffic_signs == rhs.traffic_signs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::trafficsigns::TrafficSignStatus_<ContainerAllocator1> & lhs, const ::trafficsigns::TrafficSignStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace trafficsigns

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "481cb23ff8b604083652da43030d8361";
  }

  static const char* value(const ::trafficsigns::TrafficSignStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x481cb23ff8b60408ULL;
  static const uint64_t static_value2 = 0x3652da43030d8361ULL;
};

template<class ContainerAllocator>
struct DataType< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trafficsigns/TrafficSignStatus";
  }

  static const char* value(const ::trafficsigns::TrafficSignStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"TrafficSign[] traffic_signs\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trafficsigns/TrafficSign\n"
"string category\n"
"string type\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::trafficsigns::TrafficSignStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.traffic_signs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficSignStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trafficsigns::TrafficSignStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trafficsigns::TrafficSignStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "traffic_signs[]" << std::endl;
    for (size_t i = 0; i < v.traffic_signs.size(); ++i)
    {
      s << indent << "  traffic_signs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::trafficsigns::TrafficSign_<ContainerAllocator> >::stream(s, indent + "    ", v.traffic_signs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAFFICSIGNS_MESSAGE_TRAFFICSIGNSTATUS_H
